// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rezbwjeatqupurpkodlu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJlemJ3amVhdHF1cHVycGtvZGx1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg0MjU5MTMsImV4cCI6MjA2NDAwMTkxM30.HWi2ATucNgdShOmeDNgizKWAtReNdGgdnHCQjOKAB2Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);